export const INDONESIAN_BANKS = [
    { code: 'BCA', name: 'BCA (Bank Central Asia)' },
    { code: 'MANDIRI', name: 'Bank Mandiri' },
    { code: 'BRI', name: 'BRI (Bank Rakyat Indonesia)' },
    { code: 'BNI', name: 'BNI (Bank Negara Indonesia)' },
    { code: 'BSI', name: 'BSI (Bank Syariah Indonesia)' },
    { code: 'CIMB', name: 'CIMB Niaga' },
    { code: 'CIMB_SYARIAH', name: 'CIMB Niaga Syariah' },
    { code: 'DANAMON', name: 'Bank Danamon' },
    { code: 'PERMATA', name: 'Bank Permata' },
    { code: 'BTN', name: 'BTN (Bank Tabungan Negara)' },
    { code: 'BTPN', name: 'BTPN (Bank Tabungan Pensiunan Nasional)' },
    { code: 'JENIUS', name: 'Jenius (BTPN)' },
    { code: 'MAYBANK', name: 'Maybank Indonesia' },
    { code: 'MEGA', name: 'Bank Mega' },
    { code: 'OCBC', name: 'OCBC NISP' },
    { code: 'PANIN', name: 'Bank Panin' },
    { code: 'SINARMAS', name: 'Bank Sinarmas' },
    { code: 'UOB', name: 'UOB Indonesia' },
    { code: 'BUKOPIN', name: 'Bank Bukopin' },
    { code: 'JAGO', name: 'Bank Jago' },
    { code: 'SEABANK', name: 'SeaBank' },
    { code: 'NEO', name: 'Bank Neo Commerce' },
    { code: 'ALADIN', name: 'Bank Aladin Syariah' },
    { code: 'BJB', name: 'Bank BJB' },
    { code: 'DKI', name: 'Bank DKI' },
    { code: 'JATIM', name: 'Bank Jatim' },
    { code: 'JATENG', name: 'Bank Jateng' },
    { code: 'MUAMALAT', name: 'Bank Muamalat' },
    { code: 'OTHER', name: 'Lainnya' }
];
